### PR TITLE
Flesh out the Strings page

### PR DESCRIPTION
**Pull request by blaix**

### CODE REVIEW

**Comment by blaix** [comment]
Forgot about joining strings, and want to link to core package docs for String. Going to push another commit to this soon.

**Comment by blaix** [comment]
Added the join. Haven't been able to get the right link to the package docs because the site has been down. Probably fine without. I wasn't sure if there was a way to link to a module without hard-coding to a specific version anyway.

**Comment by robinheghan** [comment]
Will wait for you to add a link to the `String` module docs before merge.

You can use `latest` in place of a version number, I believe.

**Comment by blaix** [comment]
> Will wait for you to add a link to the String module docs before merge.

Added

> You can use latest in place of a version number. Example: https://packages.gren-lang.org/package/gren-lang/core/latest/module/Maybe#withDefault

Excellent, thank you!

**Comment by robinheghan** [comment]
Thank you!

**Pull request merged**
