### PR TITLE
Support Mermaid.js

### PR DESCRIPTION
**Pull request by blaix**
This change allows you to embed [mermaid](https://mermaid.js.org/) diagrams via markdown code fences like:

```mermaid
flowchart
  A --> B
  B --> C
```

Planning to use these on the the application pages I'm writing.

### CODE REVIEW

**Comment by blaix** [comment]
using this in the source file:

Screenshot 2024-05-22 at 10 33 27 PM

**Comment by robinheghan** [comment]
`packages.gren-lang.org` supports pikchr for things like this. I forget why I didn't go with mermaid, perhaps due to backend rendering? Anyway. Would it be easy to add pikchr support instead of mermaid, alternatively add replace pikchr with mermaid on the packages site?

Would be nice of one way of doing things.

**Comment by blaix** [comment]
I agree one way would be best.

I've never seen pikchr before but it looks great. I remember mermaid being kind of limited a year or two ago and maybe that's why you went with it. Looks like pikchr is more robust but mermaid may have won the mindshare, so not sure which you'd prefer.

It looks like replacing pikchr with mermaid on the package site would be easier, since there is a markdown-it plugin for mermaid, but there is no rehype plugin for pikchr. Happy to make one though if you'd prefer to standardize on pikchr, it would just take me some time. Let me know what you think.

**Comment by robinheghan** [comment]
Hmm. I think I initially wanted mermaid, but I think it was problematic since mermaid at the time was rendered client-side (and the packages site was backend rendered). If's possible to render mermaid on the backend then I think that would be preferred. I believe pikchr is more low-level.

Would you mind testing mermaid on the packages site? If it works then I'll merge this PR.

**Comment by blaix** [comment]
Oh good point. Looks like the rehype plugin uses playwright to render on the backend. I'll test out mermaid on the package site.

**Comment by blaix** [comment]
So with this PR, the book would convert the charts to svg server-side and render the actual svg tags.

I tested mermaid on the package site using https://github.com/markslides/markslides/tree/main/packages/markdown-it-mermaid. It works, but the charts are converted client-side. The rendered HTML will look like this: https://mermaid.js.org/config/usage.html#simple-full-example

Would you be ok with that? I can send a PR for the package site if so. Would you want to remove the pikchr plugin or support both? Not sure if any packages are using that?

**Comment by robinheghan** [comment]
I'm fine with this :)

I also don't think anyone's using the pikchr support, you may go ahead and remove that.

Thanks for looking into this 💙

**Comment by robinheghan** [comment]
Let me know when you think this PR is ready to merge.

**Comment by blaix** [comment]
This PR is ready. I'll get one out for the package site soon.

**Review by robinheghan — APPROVED** [review]

**Pull request merged**
